from app import db
from models import User, Scorelist, Scorecard


user1 = User(username='JooKai', email='joo1@gmail.com')
user1.set_password('Pass1')
db.session.add(user1)
db.session.commit()
scorelist1 = Scorelist(user_id = user1.id)
db.session.add(scorelist1)
new_scorecard1 = Scorecard(score=5, uname=user1.username, scorelist_id=user1.scorelists.id, type=1)
new_scorecard2 = Scorecard(score=5, uname=user1.username, scorelist_id=user1.scorelists.id, type=2)
db.session.add(new_scorecard1)
db.session.add(new_scorecard2)
db.session.commit()

user2 = User(username='JooKai2', email='joo2@gmail.com')
user2.set_password('Pass1')
db.session.add(user2)
db.session.commit()
scorelist2 = Scorelist(user_id = user2.id)
db.session.add(scorelist2)
db.session.commit()
new_scorecard3 = Scorecard(score=10, uname=user2.username, scorelist_id=user2.scorelists.id, type=1)
new_scorecard4 = Scorecard(score=10, uname=user2.username, scorelist_id=user2.scorelists.id, type=2)
db.session.add(new_scorecard3)
db.session.add(new_scorecard4)

user3 = User(username='JooKai3', email='joo3@gmail.com')
user3.set_password('Pass1')
db.session.add(user3)
db.session.commit()
scorelist3 = Scorelist(user_id = user3.id)
db.session.add(scorelist3)
db.session.commit()
new_scorecard5 = Scorecard(score=15, uname=user3.username, scorelist_id=user3.scorelists.id, type=1)
new_scorecard6 = Scorecard(score=15, uname=user3.username, scorelist_id=user3.scorelists.id, type=2)
db.session.add(new_scorecard5)
db.session.add(new_scorecard6)

db.session.commit()